module testClustalParse

open Amyris.IO

open NUnit.Framework

let test1 = "CLUSTAL 2.0.11 multiple sequence alignment


lakdsjflsakjflsakjdflsakjdflsa      TGATCGATCGATCGTAGTCAGTCGTAGTCAGTCAGTCGTACGTACGTAGT
lAAAAAAAAAAAAAAAAAAAAAAAAAAAAA      TGATCGATCGATCGTAGTCAGTCGTAGTCAGTCAGTCGTACGTACGTAGT
                                    **************************************************

lakdsjflsakjflsakjdflsakjdflsa      CGTACGTACGTA
lAAAAAAAAAAAAAAAAAAAAAAAAAAAAA      CGTACGTACGTA
                                    ************
"

let test2="CLUSTAL 2.0.11 multiple sequence alignment


1               TGATCGATCGATCGTAGTCAGTCGTAGTCAGTCAGTCGTACGTACGTAGTCGTACGTACG
2               TGATCGATCGATCGTAGTCAGTCGTAGTCAGTCAGTCGTACGTACGTAGTCGTACGTACG
                ************************************************************

1               TA
2               TA
                **
"

let test3 = "CLUSTAL 2.0.11 multiple sequence alignment


RAM1            MRQRVGRSIARAKFINTALLGRKRPVMERVVDIAHVDSSKAIQPLMKELETDTTEARYK-
human           -------MASPSSFTYYCPPSSSPVWSEPLYSLRPEHARERLQ--DDSVETVTSIEQAK-
BET2            ------------------------------------------------------------
CDC43           -------------------------------------------------MCQATNGPSR-
COQ1            -MFQRSGAAHHIKLISSRRCRFKSSFAVALNAASKLVTPKILWNNPISLVSKEMNTLAKN
BTS1            -------------------------------------------------MEAKIDELINN
ERG9            --------MGKLLQLALHPVEMKAALKLKFCRTPLFSIYDQSTSPYLLHCFELLNLTSRS
RER2            ------------------------------------------------------------
SRT1            --------------------------------------MKIPSIIQIQFVALKRLLVETK
COQ2            -----------------------------------------MFIWQRKSILLGRSILGSG
                                                                            

RAM1            ---VLQSVLEIYDDEKN----IEPALTKEFHKMYLDVAFEISLPPQMTALDASQ----PW
human           ---VEEKIQEVFSSYKFNHLVPRLVLQREKHFHYLKRGLRQ-LTDAYECLDASR----PW
BET2            -------------------MSGSLTLLKEKHIRYIESLDTKKHNFEYWLTEHLR----LN
CDC43           ---VVTKKHRKFFERHLQLLPSSHQGHDVNRMAIIFYSISGLSIFDVNVSAKYG----DH
COQ1            IVALIGSGHPVLNKVTSYYFETEGKKVRPLLVLLLSRALSEIPMTERNHLKIDKSDVPED
BTS1            DPVWSSQNESLISKPYNHILLKPGKNFRLNLIVQINRVMNLPKDQLAIVSQIVELLHNSS
ERG9            FAAVIRELHPELRNCVTLFYLILRALDTIEDDMSIEHDLKIDLLRHFHEKLLLTKWSFDG
RER2            --------------METDSGIPGHSFVLKWTKNIFSRTLRASNCVPRHVGFIMD----GN
SRT1            EQMCFAVKSIFQRVFAWVMSLSLFSWFYVNLQNILIKALRV-GPVPEHVSFIMD----GN
COQ2            RVTVAGIIGSSRKRYTSSSSSSSSPSSKESAPVFTSKELEVARKERLDGLGPFVSR--LP
                                                                            

RAM1            MLYWIANSLKVMDRDWLSDDTKRKIVDKLFTISPSGGPFGGGPGQLSHLASTYAA-INAL
human           LCYWILHSLELLDEPIPQIVATDVCQFLELCQSPEGG-FGGGPGQYPHLAPTYAA-VNAL
BET2            GIYWGLTALCVLDSPE-TFVKEEVISFVLSCWDDKYGAFAPFPRHDAHLLTTLSA-VQIL
CDC43           LGWMRKHYIKTVLDDTENTVISGFVGSLVMNIP---------HATTINLPNTLFA-LLSM
COQ1            PIYSKPSQNQLFQRPASSISPLHILHGIKPLNPLTKGPEPLPEETFDKQRGILPK-QRRL
BTS1            LLIDDIEDNAPLRRGQ---TTSHLIFGVPSTIN---------TANYMYFRAMQLV-SQLT
ERG9            NAPDVKDRAVLTDFESILIEFHKLKPEYQEVIKEITEKMGNGMADYILDENYNLNGLQTV
RER2            RRFARKKEMDVKEGHEAGFVSMSRILELCYEAG-------------VDTATVFAFSIENF
SRT1            RRYAKSRRLPVKKGHEAGGLTLLTLLYICKRLG-------------VKCVSAYAFSIENF
COQ2            KKWIPYAELMRLEKPVGTWLLYLPCSWSILMGAMMQG-----ATLSATAGMLGIFGVGAL
                                                                            

RAM1            SLCDNIDGCWDRIDRKGIYQWLISLKEPNGGFKT---------CLEVGEVDTRGIYCALS
human           CIIG-TEEAYDIINREKLLQYLYSLKQPDGSFLM---------HVG-GEVDVRSAYCAAS
BET2            ATYDALDVLGK--DRKVRLISFIRGNQLEDGSFQ---------GDRFGEVDTRFVYTAMS
CDC43           IMLRDYEYFETILDKRSLARFVSKCQRPDRGSFVSCLDYKTNCGSSVDSDDLRFCYIAVA
COQ1            AEIVEMIHTASLLHDDVIDHSDTRRGRPSGNAAFTN-------KMAVLAGDFLLGRATVS
BTS1            TKEPLYHNLITIFNEELINLHRGQ-------------------GLDIYWRDFLPEIIPTQ
ERG9            HDYDVYCHYVAGLVGDGLTRLIVIAKFANESLYSNE-QLYESMGLFLQKTNIIRDYNEDL
RER2            KRSSREVESLMTLARERIRQITER-----------------------GELACKYGVRIKI
SRT1            NRPKEVVDTLMNLFTVKLDEFAKR---------------------AKDYKDPLYGSKIRI
COQ2            VMRGAGCTINDFLDRKLDQRVIRSVERPIASGRVS----------PRRALVFLGAQTLVG
                                                                            

RAM1            IATLLNILTEELTEG------VLNYLKNCQNYEGGFGSCPHVDEAHGGYTFCATASLAIL
human           VASLTNIITPDLFEG------TAEWIARCQNWEGGIGGVPG-MEAHGGYTFCGLAALVIL
BET2            ALSILGELTPEVVDP------AVDFVLKCYNFDGGFGLCPN-AESHAAQAFTCLGALAIA
CDC43           ILYICGCRSKEDFDEYIDTEKLLGYIMSQQCYNGAFG---AHNEPHSGYTSCALSTLALL
COQ1            ISRLHNPEVVELMSN-----SIANLVEGEFMQLKNTSIDADIDTIENGHKLLPVPSKKLE
BTS1            EMYLN----------------MVMNKTGGLFRLTLRLMEALSPSSHHGHSLVPFIN--LL
ERG9            VDGRSFWPKEIWSQYAP---QLKDFMKPENEQLGLDCINHLVLNALS-HVIDVLTYLASI
RER2            IGDLS--------------------LLDKSLLEDVRVAVETTKNNKRATLNICFPYTGRE
SRT1            VGDQS--------------------LLSPEMRKKIKKVEEITQDGDDFTLFICFPYTSRN
COQ2            MGVLSLLPAQCWWLG---LASLPIVFTYPLFKRFTYYPQAALSACFNWGALLGFPAMGVM
                                                                            

RAM1            RSMDQIN---VEKLLEWSSARQLQE-----------------------ERGFCGRSNKLV
human           KRERSLN---LKSLLQWVTSRQMRF-----------------------EGGFQGRCNKLV
BET2            NKLDMLSDDQLEEIGWWLCERQLP------------------------EGGLNGRPSKLP
CDC43           SSLEKLSDKFKEDTITWLLHRQVSSHGCMKFESELNASYDQS-----DDGGFQGRENKFA
COQ1            VKEHDFRVPSRQQGLQLSHDQIIETAFEYYIHKTYLKTAALISKSCRCAAILSGASPAVI
BTS1            GIIYQIR----DDYLNLKDFQMSSE---------------------------KGFAEDIT
ERG9            HEQSTFQFCAIPQVMAIATLALVFN-----------------------NREVLHGNVKIR
RER2            EILHAMK----ETIVQHKKGAAIDES-------------------------------TLE
SRT1            DMLHTIR----DSVEDHLENKSPRIN-----------------------------IRKFT
COQ2            SWPTMIPLYLSSYLWCMTYDTIYAHQ-------------------------DKKFDIKAG
                     :                                                      

RAM1            DGCYS-FWVGGSAAILEAFGYGQ----------CFSKHALRDYILYCCQEKEQPGLRDKP
human           DGCYS-FWQAGLLPLLHRALHAQGDPALSMSHWMFHQQALQEYILMCCQCPAG-GLLDKP
BET2            DVCYS-WWVLSSLAIIGRLDWIN-------------YEKLTEFILKCQDEKKG-GISDRP
CDC43           DTCYA-FWCLNSLHLLTKDWKML-----------CQTELVTNYLLDRTQKTLTGGFSKND
COQ1            DECYD-FGRNLGICFQLVDDMLDFTVSGK----DLGKPSGADLKLGIATAPVLFAWKEDP
BTS1            EGKLS-FPIVHALNFTKTKGQTEQ-----------HNEILRILLLRTSDKDIKLKLIQIL
ERG9            KGTTC-YLILKSRTLRGCVEIFDYYLRDIKSKLAVQDPNFLKLNIQISKIEQFMEEMYQD
RER2            SHLYT-AGVPPLDLLIRTSGVSR----------------LSDFLIWQASSKGVRIELLDC
SRT1            NKMYMGFHSNKCELLIRTSGHRR----------------LSDYMLWQVHENAT-IEFSDT
COQ2            IKSTALAWGPRTKSIMKAMSASQ------------------IALLAVAGLNSGLLWGPGF
                              :                             :               

RAM1            GAHS-DFYHTNYCLLGLAVAESSYS-CTPNDSPHNIKCTPDRLIGSSKLTDVNPVYGLPI
human           GKSR-DFYHTCYCLSGLSIAQHFGSGAMLHDVVLGVPENALQPTHPVYNIGPDKVIQATT
BET2            ENEV-DVFHTVFGVAGLSLMG------------------------YDNLVPIDPIYCMPK
CDC43           EEDA-DLYHSCLGSAALALIEG----------------------------KFNGELCIPQ
COQ1            SLGP-LISRNFSERGDVERTIDSVR------LHHGIAKTKILAEEYRDKALQNLRDSLPE
BTS1            EFDTNSLAYTKNFINQLVNMIKNDN--------------------ENKYLPDLASHSDTA
ERG9            KLPPNVKPNETPIFLKVKERSRYDD------------------ELVPTQQEEEYKFNMVL
RER2            LWPEFGPIRMAWILLKFSFHKSFLN--------------------KEYRLEEGDYDEETN
SRT1            LWPNFSFFAMYLMILKWSFFSTIQKYN-----------------EKNHSLFEKIHESVPS
COQ2            IGGLGVFAYRLFSMIKKVDLDNPKN------------------CWKYFNANINTGLYFTY
                                                                            

RAM1            ENVRKIIHYFKSNLSSPS---------
human           YFLQKPVPGFEELKDETSAEPATD---
BET2            SVTAKFKKYPYK---------------
CDC43           EIFNDFSKRCCF---------------
COQ1            SDARSALEFLTNSILTRRK--------
BTS1            TNLHDELLYIIDHLSEL----------
ERG9            SIILSVLLGFYYIYTLHRA--------
RER2            GDPIDLKEKKLN---------------
SRT1            IFKKKKTAMLLYNFPNPPISVSVTGDE
COQ2            ALAVDYILRLFGFL-------------
                    .                      
"

[<TestFixture>]
type TestClustalParse() = class 
    
    do
        ()
    [<Test>]
    member x.Test() =
        for test in [test1 ; test2 ; test3] do
            let res = Amyris.IO.clustalw.parse test
            ()


end